### ISSUE TITLE
Feature request: iOS: pull down and then swipe up to dismiss

### ISSUE THREAD

**Issue by feliperaul** [seniv/react-native-notifier#11]
On iOS, it's very common (at least on my muscle memory) to be able to pull _down_ a notification and then, while holding the finger on the screen, swipe it back up to dismiss it.

Would it be possible to add this behavior to the notification? Pulling it down and seeing it not moving at all makes it a little bit uncomfortable UX on iOS.

Btw, congrats on a great lib!

**Comment by seniv** [comment]
Hi, @feliperaul 
Do you mean to pull down to see a full message preview, or simply pull it down only for a few pixels?
It will be very helpful if you can provide a video/gif example, Thanks!
