### ISSUE TITLE
Bug for react-native-modal

### ISSUE THREAD

**Issue by kadirguloglu** [seniv/react-native-notifier#19]
It lags behind the screen when used with the [react-native-modal](https://github.com/react-native-community/react-native-modal) library

**Comment by nadav2051** [comment]
Assuming you mean the notification shows behind the backdrop of the modal, it happens to me too with react-native-modal

**Comment by seniv** [comment]
Thank you for the report!
Currently, I'm looking for the solution

**Comment by seniv** [comment]
I've just published a new version that should work well with modal when you pass `coverScreen={false}` to the `Modal` component. https://github.com/seniv/react-native-notifier/commit/1b1846e46eb05bf129bf23ef1054b30755cafa56
Please, let me know if the problem is fixed!

**Comment by kadirguloglu** [comment]
> I've just published a new version that should work well with modal when you pass `coverScreen={false}` to the `Modal` component. [1b1846e](https://github.com/seniv/react-native-notifier/commit/1b1846e46eb05bf129bf23ef1054b30755cafa56)
> Please, let me know if the problem is fixed!

I will inform you after the update. thank you for your quick solution

**Comment by kadirguloglu** [comment]
@seniv solution worked. thank you.
