### ISSUE TITLE
[feature request] Show multiple stacking notifications

### ISSUE THREAD

**Issue by nandorojo** [seniv/react-native-notifier#20]
It would be awesome to have something like this: https://vercel.com/design/toast

Try clicking "Show Toast" a few times, and then hovering over the toasts in the bottom corner.

**Comment by seniv** [comment]
Hey, good Idea!
It will be really great to have stacking available, I add a card to project's TODO list: https://github.com/seniv/react-native-notifier/projects/1#card-54877159
With current realisation of the `notifier` it will be difficult to display more then one notification at once, but I will try to do something like this in the future.

**Comment by seniv** [comment]
Closing the issue since it was added to the TODO list.

**Comment by KenzoM** [comment]
Are there any progress regarding to this?
