### ISSUE TITLE
notification can not be hidden by swiping it out in Android

### ISSUE THREAD

**Issue by shenhua123** [seniv/react-native-notifier#22]
version 1.3.2 also has this problem.

**Comment by seniv** [comment]
Hello, Can you please provide:
- screenshot of the notification
- version of RN that you use
- version of Reanimated
- is it Expo or not
- list of parameters that you use to display the notification
Thanks!

**Comment by idolago94** [comment]
Any solution for this?

**Comment by seniv** [comment]
@idolago94 Please provide additional information. Such as React Native version, Gesture Handler version, Android version, emulator or device, expo or not, and parameters of the notifier. It Will be great to see a video with the problem

**Comment by siiiiilvio** [comment]
If this happens to you, make sure that you are wrapping your application with the `GestureHandlerRootView`

`<GestureHandlerRootView><YourApp /></GestureHandlerRootView>`
