### ISSUE TITLE
NotifierComponents.Notification change background color

### ISSUE THREAD

**Issue by vineelk8** [seniv/react-native-notifier#26]
Is there an option to change background color when using NotifierComponents.Notification. Please let me know

**Comment by seniv** [comment]
Hello, @vineelk8 👋
I've just released a new version with the ability to set `containerStyle`.
Update notifier to version 1.6.0 and try to set `componentProps.containerStyle.backgroundColor`, this should help🙂

**Comment by seniv** [comment]
Closing the issue since the feature is implemented.
Feel free to re-open the issue if you have any questions.
