### ISSUE TITLE
android: alert hidden if translucent status bar

### ISSUE THREAD

**Issue by jamesholcomb** [seniv/react-native-notifier#42]
Originally referenced but closed in https://github.com/seniv/react-native-notifier/issues/7

The example app (via title="Toggle Status Bar Translucent") demonstrates alerts and notifications are partially hidden for Android if the status bar is translucent.

@seniv is there a temp workaround we can apply?

**Comment by seniv** [comment]
Hey @jamesholcomb, I have just released a new version with a new parameter `translucentStatusBar` that should fix your problem.
I have tried to make it automatically, but it looks like in React Native we can't detect that the status bar is translucent, so you should manually set the parameter to `true`.
To make it easier you can pass `translucentStatusBar` as a prop to `NotifierWrapper` or `NotifierRoot`, to use this param by default.
Hope it will help!

**Comment by jamesholcomb** [comment]
👍
