### ISSUE TITLE
[Android] SwipeEnabled not working and onPress not triggered on first press

### ISSUE THREAD

**Issue by KrifaYounes** [seniv/react-native-notifier#53]
```
    Notifier.showNotification({
            title: 'John Doe',
            description: 'Hello! Can you help me with notifications?',
            duration: 0,
            showAnimationDuration: 350,
            hideOnPress: true,
            swipeEnabled: true,
            onPress: onPress,
        });
```

    "react-native": "0.65.1",
    "react-native-notifier": "^1.7.1",
    "react-native-gesture-handler": "^1.10.3",
    "@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/drawer": "^6.1.6",
    "@react-navigation/material-top-tabs": "^6.0.4",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/stack": "^6.0.9",

**Comment by anatooly** [comment]
As for me iOS app chash when I click notification :-(

**Comment by KrifaYounes** [comment]
it's working.
I missed configure react native gesture handler

**Comment by siiiiilvio** [comment]
@KrifaYounes what did you change to get this to work?

**Comment by siiiiilvio** [comment]
If this happens to you, make sure that you are wrapping your application with the GestureHandlerRootView 

`import { GestureHandlerRootView } from 'react-native-gesture-handler';`
`<GestureHandlerRootView><YourApp /></GestureHandlerRootView>`
