### ISSUE TITLE
Notification bar overlaps the notifier.

### ISSUE THREAD

**Issue by faisalansari97** [seniv/react-native-notifier#7]
Hey seniv, thanks for this great library. I was just testing it into my expo app and i am experiencing a UI bug while showing the notifier. I am attaching the screenshot of my app screen. It would look much better if it slides more and doesn't overlap my notification bar.

![Screenshot_2020-05-15-07-03-04-522_host exp exponent](https://user-images.githubusercontent.com/25473056/82002415-5c2fc600-967b-11ea-8c86-d2a3b4802d6b.jpg)

OS: Android
Device: Redmi Note 7 Pro

**Comment by seniv** [comment]
Hey @faisalansari97, thanks for the report!
I've checked my demo on Snack, and seen that for some reasons `StatusBar` was translucent.
I have updated the Demo and added `StatusBar.setTranslucent(false);` now it should work correctly

**Comment by seniv** [comment]
I will investigate how to make this notification looks well when the status bar is translucent

**Comment by faisalansari97** [comment]
Thanks @seniv, will look forward to it.

**Comment by Fortidude** [comment]
Hi,

I have faced the same issue on android. Any ideas how to solve it?

Maybe a new prop like `topOffset` or something?
