### ISSUE TITLE
react-native-notifier onpress dont work

### ISSUE THREAD

**Issue by AhmadAl-Ghalban** [seniv/react-native-notifier#73]
Hello
When use  examples Don't Work And Don't Show notifier 
use This Code 👍 
  <View style={{ flex: 1 }}>
        <Button
            title="Long Text"
            onPress={() =>
              Notifier.showNotification({
                title: 'New request',
                duration: 6000,
                description:
                  'You just got new incoming request from John Doe, and this is a long description',
              })
            }
          />
    </View>

**Comment by ivan-khr85** [comment]
hey, @AhmadAl-Ghalban 
Do you use `NotifierWrapper` at root of project?
