### ISSUE TITLE
PanGestureHandler must be used as a descendant of GestureHandlerRootView

### ISSUE THREAD

**Issue by kaiyes** [seniv/react-native-notifier#85]
Hi, 

On Latest react native 71.7 & react navigation 6x packages, I get this error. Was working fine on react native 67 & navigation 5x packages. Any info on that ? 

![simulator_screenshot_6583D101-8189-44EA-865B-3DC130114ABB](https://github.com/seniv/react-native-notifier/assets/5293742/600a8376-616b-494e-bae7-fbdf7f5196bc)

**Comment by vineelk8** [comment]
Having the same issue with the below packages versions

"react-native": "0.71.8",
"react-native-notifier": "^1.9.0",
And react-navigation with 6x.

**Comment by danielroccha** [comment]
Same Issue here, any updates ?

**Comment by fidelsam1992** [comment]
Make sure to wrap your App with 
``` .js
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { NotifierWrapper } from "react-native-notifier";

return (
<GestureHandlerRootView style={{ flex: 1 }}>
  <NotifierWrapper>
              {/* App */}
  </NotifierWrapper>
</GestureHandlerRootView>
)
```

**Comment by seniv** [comment]
Hello,
This part was covered in the installation guide of Gesture Handler: https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js
<img width="859" alt="image" src="https://github.com/seniv/react-native-notifier/assets/18112951/d08a040e-58de-4e54-959c-2300d3d0c5cc">
And as in @fidelsam1992's example, make sure that you place `NotifierWrapper` inside `GestureHandlerRootView`, not above
